### ISSUE TITLE
Sizes are not precisely following the material design

### ISSUE THREAD

**Issue by WonderCsabo** [ernestoyaquello/vertical-stepper-form#12]
For example:

Circle size is 24dp but this lib is using 28dp
Circle text size is 12sp but this lib is using 16dp
Title text size is 14sp but this lib is using 17sp

**Comment by ernestoyaquello** [comment]
I am aware of that, but I personally prefer them like this. As I mentioned in another issue, it was never my intention to follow all the official specifications precisely.
