### ISSUE TITLE
Provide ability to customize "continue" section in the step

### ISSUE THREAD

**Issue by WonderCsabo** [ernestoyaquello/vertical-stepper-form#23]
For example in the docs, there is a "cancel" button:

![alt text](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3WHFoTnI5cy11U1E/components_acux_stepper_mblvertinpg.png)

But other projects may need other views there. It would be best to add ability to apps provide their own layout there.

**Comment by ernestoyaquello** [comment]
You can easily find, modify or even remove that view by overriding the protected method ```createStepLayout()```.

**Comment by ahikmatf** [comment]
how to override the protected method?
