### ISSUE TITLE
Custom width of element 

### ISSUE THREAD

**Issue by juliettegonzalez** [ernestoyaquello/vertical-stepper-form#27]
It would be great to have element taking the all width of the screen (MATCH_PARENT) instead of fitting the content (I'm thinking about the EditText especially) because it looks weird on tablet where there is plenty of space but the field is very short. 
When I put the layout to match parent, some problems of apparition come. 
![capture d ecran 2016-08-11 a 16 02 49](https://cloud.githubusercontent.com/assets/11295304/17591167/378d0016-5fdd-11e6-8219-ff80a9fe96f4.png)

**Comment by ernestoyaquello** [comment]
In case that you are creating the EditText views programmatically, this is the code that you need to add in order to set their witdh to ```MATCH_PARENT```:

```java
...

ViewGroup.LayoutParams editTextParams = new ViewGroup.LayoutParams(
		ViewGroup.LayoutParams.MATCH_PARENT,
		ViewGroup.LayoutParams.WRAP_CONTENT);
			
yourEditTextView.setLayoutParams(editTextParams);

...
```
Here you can see that the code works:

![width](https://cloud.githubusercontent.com/assets/2463287/17837232/f1e3809c-67a4-11e6-898a-c3f5b1b7f82b.jpg)

In case that you are using an XML file, just set the width property as usual.

**Comment by juliettegonzalez** [comment]
I am using an XML File, but in any case (I tried both), nothing is working.. My XML file looks like this (very classical) : 
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <EditText
        android:id="@+id/client_name_field"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Nom"/>

    <EditText
        android:id="@+id/client_email_field"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:inputType="textEmailAddress"
        android:hint="Email"/>

</LinearLayout>`

If you have any clue, otherwise, I'll let it that way.

**Comment by juliettegonzalez** [comment]
I am using an XML file and I already put the width as mentioned. I tried also creating it programmatically, none of them were working. 
Here is how my XML looks (very classical) :

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">`

    <EditText
        android:id="@+id/client_name_field"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Nom"/>

    <EditText
        android:id="@+id/client_email_field"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:inputType="textEmailAddress"
        android:hint="Email"/>

`</LinearLayout>`

If you have any clue of that behavior, otherwise I'll let it that way!

**Comment by MahdiAstanei** [comment]
I have the Same Problem and I use custom XML and inflate it to steps, now TextViews is getting wrap_content on run-time, what must i do?

**Comment by adriamt** [comment]
When you inflate your custom layout you can add your params dynamically and it works. I've did this and it worked.
```
        LayoutInflater inflater = LayoutInflater.from(getBaseContext());
        LinearLayout glucoseTypeLayoutContent = (LinearLayout) inflater.inflate(R.layout.step_add_glucose_event_first, null, false);
        ViewGroup.LayoutParams glucoseTypeLayoutParams = new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT);
        glucoseTypeLayoutContent.setLayoutParams(glucoseTypeLayoutParams);
```
