### ISSUE TITLE
Request option to display all items expanded with the selected results from each of the step

### ISSUE THREAD

**Issue by Danihelsan** [ernestoyaquello/vertical-stepper-form#3]
Hello Ernesto,

I will probably use your component for a MVP app. Have you consider adding the option to display all steps expanded, so that the user can change the item of the step once they are already set.

Suppose this use case with 4 steps:
1. User select all steps and confirm his selections (selections are displayed in another screen as a summary).
2. User requires to update one of the selections or more (presses summary item to open the screen with the VerticalStepperLayout).
3. User changes or updates the item already set. and confirm the changes.

I was planning on using another step like a fifth step of confirmation, which shows the summary, but i think the chance of showing all expanded would be much better.

Thanks for your hard work on this.

**Comment by ernestoyaquello** [comment]
Thanks for your suggestion! Unfortunately, I do not have time at the moment to work on this library, but I will try to add the feature you are asking for as soon as possible. In the meanwhile, you can try to implement it yourself and even send a pull request to collaborate :)

**Comment by ernestoyaquello** [comment]
Sorry, I didn't add this feature to the new version of the library, but I think that a method that opens all the fields/steps doesn't match the rest of the implementation. Once all the steps are being shown, which one is the current active step? What will be the new meaning of the next and previous buttons? Is there any logical way for allowing the user to reverse the state of the form so it can be collapsed again?

In my opinion, the best you can do is to show the user a small report that summarizes the information that is about to be submitted. Anyway, if you are very interested in this feature, you can always either extend the class ```VerticalStepperFormLayout.java``` to implement it yourself or create a branch and even make a pull request!
