### ISSUE TITLE
Not following the design guidelines for vertical steppers

### ISSUE THREAD

**Issue by EugeneHoran** [ernestoyaquello/vertical-stepper-form#4]
I think it is a good start, but it would look and feel much better following the [Material Design Guidelines for Vertical Steppers](https://material.google.com/components/steppers.html#). 

> Don’t embed steppers within steppers or use multiple steppers on one page.
Vertical Stepper Form has Vertical and Horizontal progress steppers combined.

> Should follow all of the [Design Specs](https://material.google.com/components/steppers.html#steppers-specs)

I think this library has a ton of potential. I will try to contribute as much as possible. 

Cheers 

Here is an example of the closest to the guidelines that I have created. 

![vertical steppers](https://cloud.githubusercontent.com/assets/7454787/16618571/14725726-4358-11e6-88c5-18b65a46f5ea.PNG)

**Comment by ernestoyaquello** [comment]
Check out the last version! :)
