### ISSUE TITLE
Localising labels is not supported

### ISSUE THREAD

**Issue by vihtori** [ernestoyaquello/vertical-stepper-form#5]
Hello Ernesto,

Localising the default labels used for the text elements is currently not supported. I have implemented the functionality and could provide a pull request, if you'd like to add this to the master?

**Comment by ernestoyaquello** [comment]
You can make the pull request and if everything is OK I will add it! And even if you don't do it, I will add this feature myself in the next version of the library :)

**Comment by ernestoyaquello** [comment]
The last version of the app (0.9.9) includes this feature. Check it out!
