### ISSUE TITLE
Keyboard not showing for the first EditText

### ISSUE THREAD

**Issue by younisshah** [ernestoyaquello/vertical-stepper-form#6]
I am running Android N on Google Nexus 5X. I've created an Activity with few UI controls like EditText(s), Spinner and so on. Whenever I start the Activity the soft keyboard isn't shown for the first EditText but for the other EditText(s) and Spinners. It's working fine. I tried to programmatically open the soft keyboard in 
`onStepOpening(int)` but it doesn't work.

**Comment by ernestoyaquello** [comment]
Unfortunately, the current implementation hides the keyboard by default. But as soon as I have time to work on it, I will add an option that allows you to decide whether or not the keyboard should be hidden :)

**Comment by ernestoyaquello** [comment]
In the next version of the library (I will upload it really soon), a method of the builder called ```hideKeyboard(boolean)``` will allow you to decide whether or not the software keyboard should be hidden when the steps are open. Therefore, you won't have this problem anymore!
